apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  config.yaml: |
    port: 8081
    sql:
      host: postgres.default.svc.cluster.local
      port: 5432
      username: postgres
      password: postgres
      name: postgres

